import assert from 'node:assert/strict';
import {configureRules} from '../src/duanju/engine/api';
import {newGame,declare,nextRound,clone,canAfford} from '../src/duanju/engine/interp';
import {act,shield,unit} from '../src/duanju/engine/ast';
configureRules('default');
const s=newGame(0,[{'减伤':2},{}]);
assert.deepEqual(s.side[0].cards.map(c=>c.v),[2,2,2,3]);
const sentence=[act(shield(2,unit(0)))];
assert.ok(declare(s,0,0,sentence,3));
assert.equal(s.deck[0]!['减伤'],1);
assert.ok(declare(s,0,1,sentence,3));
assert.equal(s.deck[0]!['减伤'],0);
assert.equal(canAfford(s,0,sentence,2),null);
const c=clone(s); c.advCooling[0]['减伤'][0]=99;
assert.equal(s.advCooling[0]['减伤'][0],2);
nextRound(s);
assert.equal(s.deck[0]!['减伤'],0);
assert.deepEqual(s.advCooling[0]['减伤'],[1,1]);
nextRound(s);
assert.equal(s.deck[0]!['减伤'],2);
assert.deepEqual(s.advCooling[0]['减伤'],[]);
assert.ok(canAfford(s,0,sentence,0));
assert.ok(declare(s,0,0,sentence,3));
assert.equal(s.deck[0]!['减伤'],1);
nextRound(s);assert.equal(s.deck[0]!['减伤'],1);
nextRound(s);assert.equal(s.deck[0]!['减伤'],2);
const unlimited=newGame(0);assert.ok(declare(unlimited,0,0,sentence,3));nextRound(unlimited);nextRound(unlimited);assert.equal(unlimited.deck[0],null);
console.log('冷却检查通过：四张起始牌、多副本、隔轮恢复、重复循环、深克隆、无限测试牌组');
