import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
const PORT = 5195, DBG = 9377;
const proc = spawn("/opt/pw-browsers/chromium", ["--no-sandbox", "--headless=new", `--remote-debugging-port=${DBG}`, "--user-data-dir=/tmp/claude-0/ud_tf", "--window-size=1440,810", "--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "about:blank"], { stdio: "ignore" });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
let tabs; for (let i = 0; i < 50; i++) { try { tabs = await (await fetch(`http://127.0.0.1:${DBG}/json`)).json(); if (tabs.length) break; } catch { /* */ } await sleep(300); }
const ws = new WebSocket(tabs.find((t) => t.type === "page").webSocketDebuggerUrl); await new Promise((r) => ws.addEventListener("open", r));
let id = 0; const pend = new Map(); ws.addEventListener("message", (e) => { const m = JSON.parse(e.data); if (m.id && pend.has(m.id)) { pend.get(m.id)(m); pend.delete(m.id); } });
const cdp = (method, params = {}) => new Promise((res) => { const i = ++id; pend.set(i, res); ws.send(JSON.stringify({ id: i, method, params })); });
const ev = async (x) => { const r = await cdp("Runtime.evaluate", { expression: x, awaitPromise: true, returnByValue: true }); if (r.result?.exceptionDetails) throw new Error(JSON.stringify(r.result.exceptionDetails).slice(0, 400)); return r.result?.result?.value; };
const shot = async (n) => { const r = await cdp("Page.captureScreenshot", { format: "png" }); writeFileSync(`/tmp/claude-0/tf_${n}.png`, Buffer.from(r.result.data, "base64")); console.log("shot", n); };
await cdp("Emulation.setDeviceMetricsOverride", { width: 1440, height: 810, deviceScaleFactor: 1, mobile: false });
await cdp("Page.navigate", { url: `http://127.0.0.1:${PORT}/` });
for (let i = 0; i < 80; i++) { if (await ev("!!window.__gm")) break; await sleep(500); } await sleep(1500);
await ev(`window.__btn=(t)=>[...document.querySelectorAll('button')].find(b=>b.textContent.includes(t)&&!b.disabled);{const m=document.querySelector('.mn');if(m)m.hidden=true;}__gm.open();1`);
await sleep(400); await ev(`document.querySelectorAll('.cls')[0].click();1`);
await ev(`[...document.querySelectorAll('.foe-row button')].find(b=>b.textContent.includes('90 秒')).click();1`); await sleep(200);
await ev(`__btn('开始对局').click();1`); await sleep(2500);
for (let i = 0; i < 60 && (await ev("__gm.ui")) !== "pick_unit"; i++) await sleep(500);
console.log("limit text", await ev("document.querySelector('.gm-limit')?.textContent"));
await ev("__gm.cardClicked(0);1"); await sleep(400);
for (const [t, v] of [["w", "选择"], ["n", 1], ["w", "敌方"], ["w", "造成"], ["n", 1]]) await ev(`__gm.cmp.${t === "w" ? "addWord" : "addNumber"}(${JSON.stringify(v)});__gm.renderAct();1`);
await sleep(200);
await ev(`[...document.querySelectorAll('.hs-btn')].find(b=>b.textContent.includes('拼好了')).click();1`); await sleep(400);
console.log("ui", await ev("__gm.ui"), "plate", await ev("document.querySelectorAll('.ro')[2]?.querySelector('.ro-body')?.textContent"));
await shot("1_target");
await ev("__gm.cardClicked(3);1"); await sleep(300);
console.log("ui", await ev("__gm.ui"), "plate", await ev("[...document.querySelectorAll('.ro .ro-body')].map(e=>e.textContent).join(' | ')"));
await shot("2_timing");
console.log('buttons', await ev("[...document.querySelectorAll('button')].map(b=>b.textContent).filter(t=>t.length<14).join(',')")); await ev(`__btn('撤回上一个目标').click();1`); await sleep(300);
console.log("撤回后 ui", await ev("__gm.ui"));
await ev(`__btn('返回修改句子').click();1`); await sleep(300);
console.log("返回修改 ui", await ev("__gm.ui"), "tokens", await ev("JSON.stringify(__gm.cmp.tokens.map(t=>t.v))"));
proc.kill(); process.exit(0);
